@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {
Class "<<Interface>>\nLogic"
Class LogicManager
}

package Model{
Class "<<Interface>>\nModel"
Class ModelManager
}

package Storage{
Class "<<Interface>>\nStorage"
Class StorageManager
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> "<<Interface>>\nLogic"

LogicManager .up.|> "<<Interface>>\nLogic"
ModelManager .up.|> "<<Interface>>\nModel"
StorageManager .up.|> "<<Interface>>\nStorage"

LogicManager --> "<<Interface>>\nModel"
LogicManager --> "<<Interface>>\nStorage"
@enduml
