@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Class "<<Interface>>\nUserPrefsStorage"
Class JsonUserPrefsStorage
}

Class "<<Interface>>\nStorage"
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Class "<<Interface>>\nAddressBookStorage"
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> "<<Interface>>\nStorage"

StorageManager .up.|> "<<Interface>>\nStorage"
StorageManager -up-> "1" "<<Interface>>\nUserPrefsStorage"
StorageManager -up-> "1" "<<Interface>>\nAddressBookStorage"

"<<Interface>>\nStorage" -left-|> "<<Interface>>\nUserPrefsStorage"
"<<Interface>>\nStorage" -right-|> "<<Interface>>\nAddressBookStorage"

JsonUserPrefsStorage .up.|> "<<Interface>>\nUserPrefsStorage"
JsonAddressBookStorage .up.|> "<<Interface>>\nAddressBookStorage"
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml
